site_name: 技术知识库

copyright: Copyright &copy; 2025 Qiaolook, Zhongyuan University of Technology

repo_url: https://github.com/qiaolook/Wiki
repo_name: Qiaolook/Wiki
edit_uri: edit/main/docs/

theme:

  favicon: assets/logo.png

  features:
      - announce.dismiss # 可关闭公告栏
      # - navigation.instant # 页面无刷新切换
      - navigation.prune # 只渲染可见导航项
      # - header.autohide  # 自动隐藏头部
      # - navigation.instant.progress # 页面切换进度条
      # - navigation.prune # 只渲染可见导航项
      - navigation.tracking # 滚动时URL锚点自动更新
      - navigation.tabs # 一级导航显示为顶部Tab
      # - navigation.tabs.sticky  # Tab栏吸顶
      - navigation.sections # 侧边栏分组
      - navigation.top # 返回顶部按钮
      - navigation.footer # 页脚显示在侧边栏
      - search.suggest # 搜索建议
      - search.highlight # 搜索高亮
      - search.share # 搜索结果分享
      - toc.follow # 目录跟随滚动
      # - toc.integrate # 目录集成到侧边栏
      - navigation.expand # 默认展开所有目录
      - navigation.indexes # 支持节索引页
      - content.tabs.link # 支持标签页链接
      - content.tooltips # 支持鼠标悬浮提示
      - content.code.copy # 代码块一键复制
      - content.code.select # 代码块一键全选
      # - content.action.edit # 编辑按钮
      # - content.action.view # 查看源码按钮
      - content.code.annotate # 代码注释

  custom_dir: overrides

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/lightbulb
        name: 切换深色模式
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: 切换浅色模式

  name: material
  language: zh

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/qiaolook
    - icon: /fontawesome/regular/envelope
      link: mailto:<qiaolook@outlook.com>
  analytics:
    provider: google
    property: G-R9TTTKFGQC

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  # - callouts
  - md_in_html
  - markdown.extensions.abbr # 支持Markdown文件上方自定义标题标签等
  - pymdownx.magiclink
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      # baselevel: 2
      # toc_depth: 3  # 控制标题层级深度
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - neoteroi.timeline

plugins:
  - search

nav:
  - 首页: index.md
  - 比赛介绍:
    - 比赛文件: 比赛介绍/比赛文件.md
    - 比赛心得: 比赛介绍/比赛心得.md
    - 比赛经历: 比赛介绍/比赛经历.md
  - 开发指南:
    - 简介: 开发指南/简介.md
    - 环境配置:
        - STM32CubeIDE 配置 STM32 开发环境: 开发指南/STM32CubeIDE 配置 STM32 开发环境.md
        - CubeMX + CLion 配置 STM32 开发环境: 开发指南/CubeMX + CLion 配置 STM32 开发环境.md
    - 关键技术:
        - 前言: 开发指南/前言.md
        - ZDT 电机驱动与 CAN 控制: 开发指南/ZDT 电机驱动与 CAN 控制.md
        - HWT101 陀螺仪使用: 开发指南/HWT101 陀螺仪使用.md
        - 底盘运动学正逆解算: 开发指南/底盘运动学正逆解算.md
        - 树莓派通讯: 开发指南/树莓派通讯.md
  - 硬件设计:
    - 简介: 硬件设计/简介.md
  - 预备技术:
    - 简介: 预备技术/简介.md
  - 关于: 关于.md
